### ISSUE TITLE
Facing an issue with OpenSSL at first startup / Linux

### ISSUE THREAD

**Issue by AzhamProdLive** [FallenAngel-PP/APKTool_for_5.9.X#1]
Hello, as the title says, I am facing an issue with OpenSSL when starting the program for the first time.

As I do not have any keys, the program asks me if I want to generate them :
![image](https://github.com/FallenAngel-PP/APKTool_for_5.9.X/assets/73955243/0831fe4b-776c-4558-9524-5900fc06856f)
So I press 2, then Enter in order to generate random keys, but as soon as I do that, I face an error saying this :
![image](https://github.com/FallenAngel-PP/APKTool_for_5.9.X/assets/73955243/e64cdc59-bd43-4839-8bc2-a182a87bcbff)

Problem ? OpenSSL is installed on my system, but running the 3.3.1 version : 
![image](https://github.com/FallenAngel-PP/APKTool_for_5.9.X/assets/73955243/40a14de3-7987-44de-b5c6-2897a8da25e0)

Question : Is there any way to fix this ? I'd appreciate in advance for the answer I'll get 

My computer specifications : 
- Arch Linux
- i5-10300h + RTX 3060 
- 24 Gb of RAM 
- OpenSSL 3.3.1 installed
- Java 22 installed

**Comment by AzhamProdLive** [comment]
Fixed

**Comment by FallenAngel-PP** [comment]
A new update will follow. Thanks for helping

**Comment by AzhamProdLive** [comment]
> A new update will follow. Thanks for helping

No probs

**Comment by FallenAngel-PP** [comment]
Should be solved with newest update
